development:
  adapter: postgresql
  database: blog_development
  host: localhost
  username: rails
  password: password
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: blog_test
  host: localhost
  username: rails
  password: password
  pool: 5
  timeout: 5000
